# -*- coding: utf-8 -*-
"""MajorFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107CovtIXmVbM4hTGyCoBSIltQUb46CfA
"""

!pip install ultralytics

from ultralytics import YOLO
import os

from google.colab import files
files.upload()

import os
os.makedirs("/root/.kaggle", exist_ok=True)
!mv kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d zhiaun/river-floating-trash-datasets

!rm -rf /content/dataset
!unzip river-floating-trash-datasets.zip -d /content/dataset

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/data.yaml
# path: /content/dataset/datasets/RFT
# train: images/train
# val: images/val
# 
# nc: 8
# names: ['bottle','grass','branch','milk-box','plastic-bag','plastic-garbage','ball','leaf']

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/data.yaml",
    epochs=100,
    imgsz=640,
    batch=8,
    patience=25,
    fliplr=0.5
)

# Cell 8
model.save("my_model.pt")
print("Model saved successfully!")

from google.colab import files
files.download("runs/detect/train/weights/best.pt")

from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")

metrics = model.val()

import pandas as pd

classes = metrics.names
cm_np = metrics.confusion_matrix.matrix

metrics_list = []

for i, cls in enumerate(classes):
    TP = cm_np[i, i]
    FP = cm_np[:, i].sum() - TP
    FN = cm_np[i, :].sum() - TP
    TN = cm_np.sum() - (TP + FP + FN)

    precision = TP / (TP + FP + 1e-6)
    recall = TP / (TP + FN + 1e-6)
    specificity = TN / (TN + FP + 1e-6)
    f1_score = 2 * (precision * recall) / (precision + recall + 1e-6)

    metrics_list.append([cls, TP, TN, FP, FN,
                         precision, recall, specificity, f1_score])

metrics_df = pd.DataFrame(metrics_list,
    columns=["Class","TP","TN","FP","FN",
             "Precision","Recall","Specificity","F1 Score"])

print("\nDETAILED METRICS:\n")
print(metrics_df)

# Cell 10
import numpy as np
import pandas as pd

if 'metrics' in locals() and hasattr(metrics, 'confusion_matrix') and hasattr(metrics.confusion_matrix, 'matrix'):
    cm = metrics.confusion_matrix.matrix
else:
    print("Error: metrics not found. Run model.val() first.")
    cm = None

if cm is not None:
    classes = ['bottle','grass','branch','milk-box','plastic-bag',
               'plastic-garbage','ball','leaf','background']

    try:
        cm_np = cm.cpu().numpy() if hasattr(cm, 'cpu') else np.array(cm)
        df = pd.DataFrame(cm_np, index=classes, columns=classes)

        print("\nConfusion Matrix:\n")
        print(df)

    except Exception as e:
        print(f"Error converting confusion matrix: {e}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Normalize confusion matrix (row-wise percentage)
cm_percent = cm_np.astype('float') / cm_np.sum(axis=1)[:, np.newaxis] * 100

# Create labels (count + percentage)
labels = np.empty_like(cm_np).astype(str)

for i in range(cm_np.shape[0]):
    for j in range(cm_np.shape[1]):
        count = cm_np[i, j]
        percent = cm_percent[i, j]
        labels[i, j] = f"{count}\n{percent:.1f}%"

plt.figure(figsize=(12,10))

sns.heatmap(cm_np,
            annot=labels,
            fmt="",
            cmap="YlGnBu",   # ✅ same color you want
            xticklabels=classes,
            yticklabels=classes,
            linewidths=0.5,
            linecolor='gray',
            cbar_kws={'label': 'Number of Samples'})

plt.title("Confusion Matrix (Count + Percentage)", fontsize=16, fontweight='bold')
plt.xlabel("Predicted Class", fontsize=12)
plt.ylabel("Actual Class", fontsize=12)

plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

metrics_df["Precision %"] = metrics_df["Precision"] * 100
metrics_df["Recall %"] = metrics_df["Recall"] * 100
metrics_df["Specificity %"] = metrics_df["Specificity"] * 100
metrics_df["F1 Score %"] = metrics_df["F1 Score"] * 100

import numpy as np

x = np.arange(len(metrics_df["Class"]))
width = 0.2

plt.figure(figsize=(15,7))

bars1 = plt.bar(x - 1.5*width, metrics_df["Precision %"], width, label='Precision')
bars2 = plt.bar(x - 0.5*width, metrics_df["Recall %"], width, label='Recall')
bars3 = plt.bar(x + 0.5*width, metrics_df["Specificity %"], width, label='Specificity')
bars4 = plt.bar(x + 1.5*width, metrics_df["F1 Score %"], width, label='F1 Score')

# 🔥 Add percentage labels on top
def add_labels(bars):
    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2,
                 height + 1,
                 f"{height:.1f}%",
                 ha='center', fontsize=8)

add_labels(bars1)
add_labels(bars2)
add_labels(bars3)
add_labels(bars4)

plt.xticks(x, metrics_df["Class"], rotation=45)
plt.ylabel("Percentage (%)")
plt.title("Model Performance per Class (40 Epochs)")
plt.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.plot(metrics_df["Class"], metrics_df["Precision %"], marker='o', label='Precision')
plt.plot(metrics_df["Class"], metrics_df["Recall %"], marker='o', label='Recall')
plt.plot(metrics_df["Class"], metrics_df["Specificity %"], marker='o', label='Specificity')
plt.plot(metrics_df["Class"], metrics_df["F1 Score %"], marker='o', label='F1 Score')

# Add percentage labels
for i in range(len(metrics_df)):
    plt.text(i, metrics_df["Precision %"][i]+1, f'{metrics_df["Precision %"][i]:.1f}%')
    plt.text(i, metrics_df["Recall %"][i]+1, f'{metrics_df["Recall %"][i]:.1f}%')
    plt.text(i, metrics_df["Specificity %"][i]+1, f'{metrics_df["Specificity %"][i]:.1f}%')
    plt.text(i, metrics_df["F1 Score %"][i]+1, f'{metrics_df["F1 Score %"][i]:.1f}%')

plt.title("Model Performance (Line Graph)", fontsize=16)
plt.xlabel("Classes")
plt.ylabel("Percentage (%)")

plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()

plt.tight_layout()
plt.show()

from ultralytics import YOLO
import os
from IPython.display import Image, display

# ✅ Load trained model (after 40 epochs)
model = YOLO("runs/detect/train/weights/best.pt")

# ✅ Run prediction on test images (this draws bounding boxes automatically)
results = model.predict(
    source="/content/dataset/datasets/RFT/images/test",  # your test images path
    conf=0.25,        # confidence threshold (increase for better quality)
    save=True,        # saves images with bounding boxes
    save_txt=False    # set True if you want labels also
)

print("✅ Prediction completed and saved!")

# Path where predictions are saved
base = "runs/detect"

# Find latest predict folder
preds = [f for f in os.listdir(base) if "predict" in f]
latest = sorted(preds)[-1]

print("Showing results from:", latest)

# Show first 10 images
for img in os.listdir(os.path.join(base, latest))[:20]:
    display(Image(os.path.join(base, latest, img)))

from google.colab import files
uploaded = files.upload()   # Upload best.pt here

!pip install ultralytics

from ultralytics import YOLO
import os

model = YOLO("best (4).pt")
print("Saved model loaded successfully")

import numpy as np
import pandas as pd

# Get confusion matrix
cm = metrics.confusion_matrix.matrix
classes = metrics.names

metrics_list = []

for i, cls in enumerate(classes):
    TP = cm[i, i]
    FP = cm[:, i].sum() - TP
    FN = cm[i, :].sum() - TP
    TN = cm.sum() - (TP + FP + FN)

    precision = TP / (TP + FP + 1e-6)
    recall = TP / (TP + FN + 1e-6)
    f1 = 2 * precision * recall / (precision + recall + 1e-6)
    accuracy = (TP + TN) / (cm.sum() + 1e-6)

    metrics_list.append([cls, precision, recall, f1, accuracy])

# Convert to DataFrame
metrics_df = pd.DataFrame(metrics_list, columns=[
    "Class", "Precision", "Recall", "F1 Score", "Accuracy"
])

# Convert to percentage
metrics_df["Precision %"] = metrics_df["Precision"] * 100
metrics_df["Recall %"] = metrics_df["Recall"] * 100
metrics_df["F1 Score %"] = metrics_df["F1 Score"] * 100
metrics_df["Accuracy %"] = metrics_df["Accuracy"] * 100

print(metrics_df)

# Overall metrics (average)
overall_precision = metrics_df["Precision"].mean()
overall_recall = metrics_df["Recall"].mean()
overall_f1 = metrics_df["F1 Score"].mean()
overall_accuracy = metrics_df["Accuracy"].mean()

print("\n===== OVERALL MODEL PERFORMANCE =====")
print(f"Precision: {overall_precision*100:.2f}%")
print(f"Recall: {overall_recall*100:.2f}%")
print(f"F1 Score: {overall_f1*100:.2f}%")
print(f"Accuracy (Model Performance): {overall_accuracy*100:.2f}%")

# 🔹 Install
!pip install gradio

import gradio as gr
import sqlite3
import hashlib
from PIL import Image
import numpy as np

# =========================
# 🔍 Load YOLO Model
# =========================
try:
    model
except NameError:
    try:
        model = yolo_model
    except:
        raise Exception("❌ Model not found. Check your model variable name.")

# =========================
# 🗄️ Database Setup
# =========================
conn = sqlite3.connect("users.db", check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    password TEXT
)
""")
conn.commit()

# =========================
# 🔐 Password Hash Function
# =========================
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# =========================
# 📝 Signup Function
# =========================
def signup(username, password):

    if username == "" or password == "":
        return "⚠️ Please fill all fields"

    cursor.execute("SELECT * FROM users WHERE username=?", (username,))
    existing_user = cursor.fetchone()

    if existing_user:
        return "❌ Username already exists"

    hashed_pwd = hash_password(password)

    cursor.execute(
        "INSERT INTO users VALUES (?, ?)",
        (username, hashed_pwd)
    )

    conn.commit()

    return "✅ Signup Successful"

# =========================
# 🔑 Login Function
# =========================
def login(username, password):

    hashed_pwd = hash_password(password)

    cursor.execute(
        "SELECT * FROM users WHERE username=? AND password=?",
        (username, hashed_pwd)
    )

    user = cursor.fetchone()

    if user:
        return (
            gr.update(visible=True),
            gr.update(visible=False),
            f"✅ Welcome {username}"
        )

    return (
        gr.update(visible=False),
        gr.update(visible=True),
        "❌ Invalid Username or Password"
    )

# =========================
# 🚪 Logout Function
# =========================
def logout():
    return (
        gr.update(visible=False),
        gr.update(visible=True),
        "👋 Logged Out Successfully"
    )

# =========================
# 🔍 Detection Function
# =========================
def predict_image(image):

    img = Image.fromarray(image)

    results = model(img)

    output_img = results[0].plot()

    labels = []

    try:
        boxes = results[0].boxes

        for box in boxes:
            cls = int(box.cls[0])
            conf = float(box.conf[0])

            name = model.names[cls]

            labels.append(f"{name} ({conf:.2f})")

    except:
        labels.append("No objects detected")

    label_text = "\n".join(labels)

    return output_img, label_text

# =========================
# 🎨 Custom CSS
# =========================
custom_css = """
body {
    background-color: #e6f2ff;
}

.gradio-container {
    background-color: #e6f2ff !important;
}

h1, h2, p {
    color: #003366 !important;
}

button {
    background-color: #3399ff !important;
    color: white !important;
    border-radius: 10px !important;
    font-size: 16px !important;
}

textarea, input {
    border-radius: 8px !important;
}
"""

# =========================
# 🚀 UI
# =========================
with gr.Blocks(css=custom_css) as demo:

    gr.Markdown("# 🌊 River Trash Detection System")

    # =====================
    # AUTH SECTION
    # =====================
    with gr.Column(visible=True) as auth_section:

        with gr.Tab("🔑 Login"):

            login_user = gr.Textbox(label="Username")
            login_pass = gr.Textbox(
                label="Password",
                type="password"
            )

            login_btn = gr.Button("Login")

        with gr.Tab("📝 Sign Up"):

            signup_user = gr.Textbox(label="Create Username")

            signup_pass = gr.Textbox(
                label="Create Password",
                type="password"
            )

            signup_btn = gr.Button("Sign Up")

        auth_status = gr.Textbox(label="Status")

    # =====================
    # MAIN APP
    # =====================
    with gr.Column(visible=False) as main_app:

        gr.Markdown("## ♻️ Upload Image for Trash Detection")

        image_input = gr.Image(
            type="numpy",
            label="Upload River Image"
        )

        detect_btn = gr.Button("Detect Trash")

        output_image = gr.Image(label="Detection Output")

        output_text = gr.Textbox(
            label="Detected Objects"
        )

        logout_btn = gr.Button("Logout")

    # =====================
    # ACTIONS
    # =====================

    signup_btn.click(
        signup,
        inputs=[signup_user, signup_pass],
        outputs=auth_status
    )

    login_btn.click(
        login,
        inputs=[login_user, login_pass],
        outputs=[main_app, auth_section, auth_status]
    )

    logout_btn.click(
        logout,
        outputs=[main_app, auth_section, auth_status]
    )

    detect_btn.click(
        predict_image,
        inputs=image_input,
        outputs=[output_image, output_text]
    )

# =========================
# 🌐 Launch
# =========================
demo.launch(share=True)